[tox]
envlist =
    py310,py311,py312,py313,py314,lint

[testenv]
passenv = DB,DBURI
commands =
    {envpython} setup.py clean --all
    pytest --cov=rdflib_sqlalchemy

deps =
    pytest>=3.4.0
    pytest-cov>=2.5.1
    psycopg2
    mysqlclient

[testenv:lint]
commands = flake8 rdflib_sqlalchemy test
deps =
    flake8

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, lint
    3.14: py314

[flake8]
max-line-length = 120
max-complexity = 15
ignore = W504,W503,E128
